source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'PJQuicklyDev' do
    pod 'Alamofire', '~> 4.5.1'
    pod 'Kingfisher', '~> 4.1.1'
    #pod 'SnapKit', '~> 4.0.0'
    pod 'MJRefresh', '~> 3.1.14'
    pod 'SVProgressHUD'
    #pod 'SwiftyJSON', '~> 4.0.0-alpha.1'
    #pod 'ObjectMapper', '~> 3.1.0'
    pod 'HandyJSON', '~> 4.0.0-beta.1'
    pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
    pod 'NSLogger/Swift', '~> 1.8.3'
    pod 'CryptoSwift', '~> 0.8.0'
    pod 'FSPagerView', '~> 0.7.1'
end
