#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'
use_frameworks!

target 'PJQuicklyDev' do
    pod 'Alamofire', '~> 5.2.2'
    pod 'Kingfisher', '~> 5.15.0'
    pod 'MJRefresh', '~> 3.5.0'
    pod 'SVProgressHUD'
    pod 'HandyJSON', '~> 5.0.2'
    pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
    pod 'CryptoSwift', '~> 1.3.1'
    pod 'FSPagerView', '~> 0.8.3'
    pod 'CocoaLumberjack/Swift', '~> 3.6.2'
    pod 'ReachabilitySwift', '~> 5.0.0'
end
